dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: heroku-travis
  strategy: git
  api_key:
    secure: knwibtiH3Di+nJANwrBtV58CnNmvJKLdvqE3BjpIye4NOS0PaK4guUGEuzCieZBMW18Zbcm7WodYtw7Xf2j/GSVC8RdFjK3hUVrEFGkngLCWDJJtc/HDyN2fZAh0/Ll7G8k+D895OhEUi0b+d4OyrTfTC0XWMkoiXyZUltO8PUHTC6XgQzGY3y1DkiB7rH6pxAeAokvDLWu6AUZI9O9Ihx8tUIntKkDVGl86Kh+qq26vbFgOyQvzPmsmPJigJkuT51K0wZc8t8POSABQTbz9W/LOdVPnBCxWqNN8TPKmWVv8OAo8ap75ZVGCsgCP2+GRrOdsf+Q+QAck/5NLuOAtqTYWH6j5inCWQOXe6rzBelNm3bGzij7hiA3+Ecdv207fg/IoUxm7qEM6X2/utEoqFO8KUdLeJReEDgwxYvCZzeQaZVle+EvmK8g3jhvRW9JzoSfiAEZk2QMPy0dQ5wBGch/stg1N7LVYoJ3+bemxume2tUMgiRJid48otn7/9ujmienu4hAa/3fK4wgjANyn6GA2zSvNVoPABaaFk7+fHzfr+OAIXS+PoG7zPoZfOzdQYBxze+Iemm6IAKykoIIS3tdHQLISAlXitg4MrnD4DhscZZ/wjrGQKWFh1HhRwAgp87A5jEu5/9yilWBh1i2QOVL8sQaHF1eDlx0eRyp8H0Y=
