dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: heroku-travis
  strategy: git
  api_key:
    secure: OakeF9AebOmGFofIyhzk9pH6xZvDxGtcR76dIqQtsnLCahLeNfItRN1WYT+INLT+bNZIX5zyTxh1RVNAOKN+/ABpi8A4vDUUXYTrdvO89EwkZXzeRYlcRfpZp1K6Jd8qJ5mMAH1euXVcbLa0d0H2Oooo8nO55WFWR9Ngy0lmXMRr/LBIAvzvUUYi+cQo9svV9JbOc3dTYL9BAaEZt7Zpq4+lpQg4JBIUgK3ZW8W8f2Oh15UIYILDbPVT9PrTRcRwHuDXnSwPinDux0n1Tvor2kaCIrZYxJiIckv4bgK5hxnn5hXJZOCZO2oeyxZ4Xf3JSwrL9I+Dzxvzt5Js2Pr4sfQkE4O5JS3ucoT0xUKtZEKpm5eNmRWU2hu5K9F6IUibZcBcW61iUR3A8Y+MgHrrNfmtOl6E6SRdEr3Q05yn4FvZrdyY9HkS56JNd8uz9T+L8GPUD806SEw8XpTKBfdwmcV1xXDq0/CWtF7x4mP1xlG836C4OC46unN9kjhZG63IYC/Xy4mMwsURa/hrPm0pU8ebkNSFV8RDp+BM8z1zxqtDFOzYJiugzeMbsfeHwSX/9XImwfW/UZ7ocF5Nj1NEQ23bwRQupgIThpLVj6toArCzCQwsO9mgphr4Ij2GB5DDAXbEeKuHdIi5AzUui2LrpQnUUe1V9POu1/V8ONslXXM=
